version: "3.8"
services:
  web:
    build: ./app
    image: 853259391877.dkr.ecr.us-west-1.amazonaws.com/django_docker_aws:django_docker_aws_web
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    environment:
      - DB_NAME=btredb
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=btredb.cdeoitc1qcan.us-west-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-52-53-48-199.us-west-1.compute.amazonaws.com
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 853259391877.dkr.ecr.us-west-1.amazonaws.com/django_docker_aws \
          :django_docker_aws_nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 8000:80
    depends_on:
      - web
volumes:
  static_volume: